version: '3.9'

volumes:
  logs:
    driver: local
  data:

x-common-variables: &common-variables
  TZ: America/Sao_Paulo

services:
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    tty: true
    container_name: cccat20
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src
    environment:
      <<: *common-variables
    depends_on:
      - postgres
    ports:
      - "8089:8089"
    command: air

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
